export const ADDTODO = "ADDTODO";
export const INPUTCHANGE = "INPUTCHANGE";
export const TOGGLECOMPLETION = "TOGGLECOMPLETION";
export const DELETETODO = "DELETETODO";
export const DISPLAYALERT = "DISPLAYALERT"
